language: ruby

rvm:
- 2.1

script: ./script/cibuild

before_install:
  - gem install liquid -v 2.5.1 --no-rdoc --no-ri
  - gem install jekyll -v 1.0.2 --no-rdoc --no-ri

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
